services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${KEY_POSTGRES_DB}
      POSTGRES_USER: ${KEY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEY_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    environment:
      KEY_POSTGRES_HOST: db

    ports:
      - 8080:8080

volumes:
  postgres_data:
